# Generated by Django 3.1 on 2020-09-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20, verbose_name='商品')),
                ('barcode', models.CharField(max_length=100, verbose_name='条形码')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('date', models.DateField(verbose_name='时间')),
                ('location', models.CharField(max_length=100, verbose_name='地点')),
                ('note', models.CharField(max_length=100, verbose_name='备注')),
            ],
        ),
    ]
