# Generated by Django 3.1 on 2020-09-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='product',
            field=models.CharField(max_length=100, verbose_name='商品'),
        ),
    ]
